name: Maven Build Workflow  # Name of the Workflow

# Trigger the workflow on push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  maven-build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu image

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version of checkout

      # Step 2: Set up Java Development Kit (JDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use Java 11
          distribution: 'zulu'  # Use Zulu OpenJDK

      # Step 3: Run Maven commands sequentially
      - name: Run Maven Build Goals
        run: |
          mvn clean           # Clean the project
          mvn validate        # Validate the project
          mvn compile         # Compile the code
          mvn test            # Run tests
          mvn package         # Package the project
          mvn verify          # Verify the package
          mvn install         # Install the artifact
          mvn deploy          # Deploy the artifact
          mvn site            # Generate the site
          
      # Step 4: Display output after execution
      - name: Display Maven Output
        run: echo "All 9 Maven goals have been executed!"
