name: Maven Build Workflow

on:
  push:
    branches:
      - main

jobs:
  maven-build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Navigate to the project directory
        run: cd project  # Replace 'project' with the correct directory

      - name: Run Maven Build Goals
        run: |
          mvn clean           # Clean the project
          mvn validate        # Validate the project
          mvn compile         # Compile the code
          mvn test            # Run tests
          mvn package         # Package the project
          mvn verify          # Verify the package
          mvn install         # Install the artifact
          mvn deploy          # Deploy the artifact
          mvn site            # Generate the site

      - name: Display Maven Output
        run: echo "All 9 Maven goals have been executed!"
